# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Dashboard.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QHBoxLayout,
    QLabel, QLayout, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStackedWidget,
    QStatusBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(985, 807)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.frame1 = QFrame(self.centralwidget)
        self.frame1.setObjectName(u"frame1")
        self.frame1.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame1.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayoutWidget = QWidget(self.frame1)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(0, -50, 241, 801))
        self.verticalLayout6 = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout6.setObjectName(u"verticalLayout6")
        self.verticalLayout6.setSizeConstraint(QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout6.setContentsMargins(1, 1, 1, 1)
        self.btnAdministrador = QPushButton(self.verticalLayoutWidget)
        self.btnAdministrador.setObjectName(u"btnAdministrador")
        font = QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.btnAdministrador.setFont(font)
        self.btnAdministrador.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.btnAdministrador.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout6.addWidget(self.btnAdministrador)

        self.btnLogistico = QPushButton(self.verticalLayoutWidget)
        self.btnLogistico.setObjectName(u"btnLogistico")
        self.btnLogistico.setFont(font)
        self.btnLogistico.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.btnLogistico.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout6.addWidget(self.btnLogistico)

        self.btnVehicles = QPushButton(self.verticalLayoutWidget)
        self.btnVehicles.setObjectName(u"btnVehicles")
        self.btnVehicles.setFont(font)
        self.btnVehicles.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.btnVehicles.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout6.addWidget(self.btnVehicles)

        self.btnIngenieria = QPushButton(self.verticalLayoutWidget)
        self.btnIngenieria.setObjectName(u"btnIngenieria")
        self.btnIngenieria.setFont(font)
        self.btnIngenieria.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.btnIngenieria.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout6.addWidget(self.btnIngenieria)

        self.btnMarketing = QPushButton(self.verticalLayoutWidget)
        self.btnMarketing.setObjectName(u"btnMarketing")
        self.btnMarketing.setFont(font)
        self.btnMarketing.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.btnMarketing.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout6.addWidget(self.btnMarketing)

        self.btnUsers = QPushButton(self.verticalLayoutWidget)
        self.btnUsers.setObjectName(u"btnUsers")
        self.btnUsers.setFont(font)
        self.btnUsers.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.btnUsers.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout6.addWidget(self.btnUsers)

        self.verticalLayout6.setStretch(1, 1)
        self.verticalLayout6.setStretch(2, 1)
        self.verticalLayout6.setStretch(3, 1)
        self.verticalLayout6.setStretch(4, 1)
        self.verticalLayout6.setStretch(5, 1)
        self.stackedWidget = QStackedWidget(self.frame1)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(239, -1, 731, 701))
        self.page1 = QWidget()
        self.page1.setObjectName(u"page1")
        self.lblTituloEmpleados = QLabel(self.page1)
        self.lblTituloEmpleados.setObjectName(u"lblTituloEmpleados")
        self.lblTituloEmpleados.setGeometry(QRect(0, -10, 721, 81))
        font1 = QFont()
        font1.setPointSize(36)
        font1.setBold(True)
        self.lblTituloEmpleados.setFont(font1)
        self.lblTituloEmpleados.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lblTituloEmpleados.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.stackedWidget_2 = QStackedWidget(self.page1)
        self.stackedWidget_2.setObjectName(u"stackedWidget_2")
        self.stackedWidget_2.setGeometry(QRect(9, 89, 721, 671))
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.txtNombre = QLineEdit(self.page_3)
        self.txtNombre.setObjectName(u"txtNombre")
        self.txtNombre.setGeometry(QRect(200, 90, 511, 31))
        self.txtEmail = QLineEdit(self.page_3)
        self.txtEmail.setObjectName(u"txtEmail")
        self.txtEmail.setGeometry(QRect(200, 160, 511, 31))
        self.txtTelefono = QLineEdit(self.page_3)
        self.txtTelefono.setObjectName(u"txtTelefono")
        self.txtTelefono.setGeometry(QRect(200, 240, 511, 31))
        self.txtIdEmpleado = QLineEdit(self.page_3)
        self.txtIdEmpleado.setObjectName(u"txtIdEmpleado")
        self.txtIdEmpleado.setGeometry(QRect(200, 320, 511, 31))
        self.txtCargo = QLineEdit(self.page_3)
        self.txtCargo.setObjectName(u"txtCargo")
        self.txtCargo.setGeometry(QRect(200, 410, 511, 31))
        self.txtAnioIngreso = QLineEdit(self.page_3)
        self.txtAnioIngreso.setObjectName(u"txtAnioIngreso")
        self.txtAnioIngreso.setGeometry(QRect(200, 480, 511, 31))
        self.txtGenero = QLineEdit(self.page_3)
        self.txtGenero.setObjectName(u"txtGenero")
        self.txtGenero.setGeometry(QRect(200, 550, 511, 31))
        self.layoutWidget = QWidget(self.page_3)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(20, 60, 148, 551))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.layoutWidget)
        self.label_2.setObjectName(u"label_2")
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        self.label_2.setFont(font2)
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout_2.addWidget(self.label_2)

        self.label_3 = QLabel(self.layoutWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font2)
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_3)

        self.label_4 = QLabel(self.layoutWidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font2)
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_4)

        self.label_5 = QLabel(self.layoutWidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setFont(font2)
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_5)

        self.label_6 = QLabel(self.layoutWidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFont(font2)
        self.label_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_6)

        self.label_7 = QLabel(self.layoutWidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setFont(font2)
        self.label_7.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_7)

        self.label_8 = QLabel(self.layoutWidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setFont(font2)
        self.label_8.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_8)

        self.pushButton_9 = QPushButton(self.page_3)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(390, 20, 131, 31))
        font3 = QFont()
        font3.setPointSize(16)
        font3.setBold(True)
        self.pushButton_9.setFont(font3)
        self.pushButton_9.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.pushButton_9.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_7 = QPushButton(self.page_3)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(560, 20, 131, 31))
        self.pushButton_7.setFont(font3)
        self.pushButton_7.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.pushButton_7.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_6 = QPushButton(self.page_3)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(60, 20, 131, 31))
        self.pushButton_6.setFont(font3)
        self.pushButton_6.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.pushButton_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_8 = QPushButton(self.page_3)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(220, 20, 131, 31))
        self.pushButton_8.setFont(font3)
        self.pushButton_8.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.pushButton_8.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.stackedWidget_2.addWidget(self.page_4)
        self.stackedWidget.addWidget(self.page1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label = QLabel(self.page_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(290, 20, 101, 51))
        font4 = QFont()
        font4.setPointSize(28)
        font4.setBold(True)
        self.label.setFont(font4)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.verticalLayoutWidget_2 = QWidget(self.page_2)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(189, 69, 541, 641))
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setSpacing(30)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(3, 6, 4, 3)
        self.txtVINSerialNo = QLineEdit(self.verticalLayoutWidget_2)
        self.txtVINSerialNo.setObjectName(u"txtVINSerialNo")

        self.verticalLayout_4.addWidget(self.txtVINSerialNo)

        self.txtMarca = QLineEdit(self.verticalLayoutWidget_2)
        self.txtMarca.setObjectName(u"txtMarca")

        self.verticalLayout_4.addWidget(self.txtMarca)

        self.txtModelo = QLineEdit(self.verticalLayoutWidget_2)
        self.txtModelo.setObjectName(u"txtModelo")

        self.verticalLayout_4.addWidget(self.txtModelo)

        self.txtAnio = QLineEdit(self.verticalLayoutWidget_2)
        self.txtAnio.setObjectName(u"txtAnio")

        self.verticalLayout_4.addWidget(self.txtAnio)

        self.txtEngineType = QLineEdit(self.verticalLayoutWidget_2)
        self.txtEngineType.setObjectName(u"txtEngineType")

        self.verticalLayout_4.addWidget(self.txtEngineType)

        self.txtTransmision = QLineEdit(self.verticalLayoutWidget_2)
        self.txtTransmision.setObjectName(u"txtTransmision")

        self.verticalLayout_4.addWidget(self.txtTransmision)

        self.txtKilometraje = QLineEdit(self.verticalLayoutWidget_2)
        self.txtKilometraje.setObjectName(u"txtKilometraje")

        self.verticalLayout_4.addWidget(self.txtKilometraje)

        self.txtEstado = QLineEdit(self.verticalLayoutWidget_2)
        self.txtEstado.setObjectName(u"txtEstado")

        self.verticalLayout_4.addWidget(self.txtEstado)

        self.txtUltimoMantenimiento = QLineEdit(self.verticalLayoutWidget_2)
        self.txtUltimoMantenimiento.setObjectName(u"txtUltimoMantenimiento")

        self.verticalLayout_4.addWidget(self.txtUltimoMantenimiento)

        self.layoutWidget1 = QWidget(self.page_2)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(8, 65, 182, 641))
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_9 = QLabel(self.layoutWidget1)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setFont(font2)
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_9)

        self.label_10 = QLabel(self.layoutWidget1)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setFont(font2)
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_10)

        self.label_11 = QLabel(self.layoutWidget1)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setFont(font2)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_11)

        self.label_12 = QLabel(self.layoutWidget1)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setFont(font2)
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_12)

        self.label_13 = QLabel(self.layoutWidget1)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setFont(font2)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_13)

        self.label_14 = QLabel(self.layoutWidget1)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setFont(font2)
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_14)

        self.label_15 = QLabel(self.layoutWidget1)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setFont(font2)
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_15)

        self.label_16 = QLabel(self.layoutWidget1)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setFont(font2)
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_16)

        self.label_17 = QLabel(self.layoutWidget1)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setFont(font2)
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_17)

        self.stackedWidget.addWidget(self.page_2)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.visual_page_widget = QFrame(self.page_5)
        self.visual_page_widget.setObjectName(u"visual_page_widget")
        self.visual_page_widget.setGeometry(QRect(-1, 19, 751, 691))
        self.visual_page_widget.setFrameShape(QFrame.Shape.StyledPanel)
        self.visual_page_widget.setFrameShadow(QFrame.Shadow.Raised)
        self.stackedWidget.addWidget(self.page_5)
        self.pageIngenieria = QWidget()
        self.pageIngenieria.setObjectName(u"pageIngenieria")
        self.Ingebuton_4 = QPushButton(self.pageIngenieria)
        self.Ingebuton_4.setObjectName(u"Ingebuton_4")
        self.Ingebuton_4.setGeometry(QRect(380, 60, 131, 31))
        self.Ingebuton_4.setFont(font3)
        self.Ingebuton_4.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.Ingebuton_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Ingebuton_3 = QPushButton(self.pageIngenieria)
        self.Ingebuton_3.setObjectName(u"Ingebuton_3")
        self.Ingebuton_3.setGeometry(QRect(210, 60, 131, 31))
        self.Ingebuton_3.setFont(font3)
        self.Ingebuton_3.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.Ingebuton_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Ingebuton = QPushButton(self.pageIngenieria)
        self.Ingebuton.setObjectName(u"Ingebuton")
        self.Ingebuton.setGeometry(QRect(50, 60, 131, 31))
        self.Ingebuton.setFont(font3)
        self.Ingebuton.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.Ingebuton.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Ingebuton_5 = QPushButton(self.pageIngenieria)
        self.Ingebuton_5.setObjectName(u"Ingebuton_5")
        self.Ingebuton_5.setGeometry(QRect(550, 60, 131, 31))
        self.Ingebuton_5.setFont(font3)
        self.Ingebuton_5.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.Ingebuton_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Ingebuton_2 = QLineEdit(self.pageIngenieria)
        self.Ingebuton_2.setObjectName(u"Ingebuton_2")
        self.Ingebuton_2.setGeometry(QRect(60, 120, 121, 31))
        font5 = QFont()
        font5.setPointSize(11)
        font5.setBold(True)
        self.Ingebuton_2.setFont(font5)
        self.Ingebuton_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Ingebox = QComboBox(self.pageIngenieria)
        self.Ingebox.addItem("")
        self.Ingebox.addItem("")
        self.Ingebox.addItem("")
        self.Ingebox.addItem("")
        self.Ingebox.addItem("")
        self.Ingebox.setObjectName(u"Ingebox")
        self.Ingebox.setGeometry(QRect(220, 120, 141, 24))
        self.Ingebuton_6 = QPushButton(self.pageIngenieria)
        self.Ingebuton_6.setObjectName(u"Ingebuton_6")
        self.Ingebuton_6.setGeometry(QRect(400, 113, 101, 41))
        self.Ingeline = QLineEdit(self.pageIngenieria)
        self.Ingeline.setObjectName(u"Ingeline")
        self.Ingeline.setGeometry(QRect(560, 120, 113, 31))
        self.Ingeline.setFont(font5)
        self.Ingeline.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame = QFrame(self.pageIngenieria)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(-1, 179, 741, 521))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.stackedWidget.addWidget(self.pageIngenieria)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.btn_me_gusta = QPushButton(self.page_6)
        self.btn_me_gusta.setObjectName(u"btn_me_gusta")
        self.btn_me_gusta.setGeometry(QRect(520, 620, 171, 71))
        self.btn_me_gusta.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.btn_no_gusta = QPushButton(self.page_6)
        self.btn_no_gusta.setObjectName(u"btn_no_gusta")
        self.btn_no_gusta.setGeometry(QRect(30, 620, 171, 71))
        self.btn_no_gusta.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.btn_siguiente = QPushButton(self.page_6)
        self.btn_siguiente.setObjectName(u"btn_siguiente")
        self.btn_siguiente.setGeometry(QRect(368, 640, 111, 41))
        self.btn_siguiente.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        icon = QIcon(QIcon.fromTheme(u"go-next"))
        self.btn_siguiente.setIcon(icon)
        self.btn_anterior = QPushButton(self.page_6)
        self.btn_anterior.setObjectName(u"btn_anterior")
        self.btn_anterior.setGeometry(QRect(230, 640, 111, 41))
        self.btn_anterior.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        icon1 = QIcon(QIcon.fromTheme(u"go-previous"))
        self.btn_anterior.setIcon(icon1)
        self.label_publicidad = QLabel(self.page_6)
        self.label_publicidad.setObjectName(u"label_publicidad")
        self.label_publicidad.setGeometry(QRect(8, 15, 721, 591))
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.label_18 = QLabel(self.page_7)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(-2, 5, 441, 351))
        self.btnCompra = QPushButton(self.page_7)
        self.btnCompra.setObjectName(u"btnCompra")
        self.btnCompra.setGeometry(QRect(490, 140, 171, 121))
        self.btnNoCompra = QPushButton(self.page_7)
        self.btnNoCompra.setObjectName(u"btnNoCompra")
        self.btnNoCompra.setGeometry(QRect(490, 507, 171, 121))
        self.btnLista = QPushButton(self.page_7)
        self.btnLista.setObjectName(u"btnLista")
        self.btnLista.setGeometry(QRect(490, 340, 171, 61))
        self.label_19 = QLabel(self.page_7)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(0, 360, 441, 341))
        self.stackedWidget.addWidget(self.page_7)
        self.btnConfirmarCRUD = QPushButton(self.frame1)
        self.btnConfirmarCRUD.setObjectName(u"btnConfirmarCRUD")
        self.btnConfirmarCRUD.setGeometry(QRect(440, 690, 331, 61))
        self.btnConfirmarCRUD.setFont(font)
        self.btnConfirmarCRUD.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.btnConfirmarCRUD.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.horizontalLayout.addWidget(self.frame1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 985, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(5)
        self.stackedWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btnAdministrador.setText(QCoreApplication.translate("MainWindow", u"Administrador", None))
        self.btnLogistico.setText(QCoreApplication.translate("MainWindow", u"Logistica", None))
        self.btnVehicles.setText(QCoreApplication.translate("MainWindow", u"Visual", None))
        self.btnIngenieria.setText(QCoreApplication.translate("MainWindow", u"Ingenieria", None))
        self.btnMarketing.setText(QCoreApplication.translate("MainWindow", u"Marketing", None))
        self.btnUsers.setText(QCoreApplication.translate("MainWindow", u"Usuarios", None))
        self.lblTituloEmpleados.setText(QCoreApplication.translate("MainWindow", u"Gest\u00edon De Empleados", None))
        self.txtAnioIngreso.setText("")
        self.txtAnioIngreso.setPlaceholderText(QCoreApplication.translate("MainWindow", u"A\u00f1o/Mes/Dia", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Nombre Completo:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Email:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Telefono:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"ID Empleado:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Cargo:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"A\u00f1o De Ingreso:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Genero:", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Obtener", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Eliminar", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"A\u00f1adir", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Editar", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Stock", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"VIN/Serial NO:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Marca:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Modelo:", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"A\u00f1o:", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Engine type:", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Transmision:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Kilometraje:", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Estado:", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Ultimo mantenimiento:", None))
        self.Ingebuton_4.setText(QCoreApplication.translate("MainWindow", u"Datos", None))
        self.Ingebuton_3.setText(QCoreApplication.translate("MainWindow", u"Editar", None))
        self.Ingebuton.setText(QCoreApplication.translate("MainWindow", u"A\u00f1adir", None))
        self.Ingebuton_5.setText(QCoreApplication.translate("MainWindow", u"Tiempo", None))
        self.Ingebuton_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ID del vehiculo", None))
        self.Ingebox.setItemText(0, QCoreApplication.translate("MainWindow", u"Que desea?", None))
        self.Ingebox.setItemText(1, QCoreApplication.translate("MainWindow", u"Reparar", None))
        self.Ingebox.setItemText(2, QCoreApplication.translate("MainWindow", u"Mantener estado", None))
        self.Ingebox.setItemText(3, QCoreApplication.translate("MainWindow", u"Reciclarlo", None))
        self.Ingebox.setItemText(4, "")

        self.Ingebuton_6.setText(QCoreApplication.translate("MainWindow", u"Grafica", None))
        self.Ingeline.setPlaceholderText(QCoreApplication.translate("MainWindow", u"En reparacion", None))
        self.btn_me_gusta.setText(QCoreApplication.translate("MainWindow", u"Me Gusto", None))
        self.btn_no_gusta.setText(QCoreApplication.translate("MainWindow", u"No Me Gusto", None))
        self.btn_siguiente.setText(QCoreApplication.translate("MainWindow", u"Adelante", None))
        self.btn_anterior.setText(QCoreApplication.translate("MainWindow", u"Atras", None))
        self.label_publicidad.setText("")
        self.label_18.setText("")
        self.btnCompra.setText(QCoreApplication.translate("MainWindow", u"Comprar", None))
        self.btnNoCompra.setText(QCoreApplication.translate("MainWindow", u"No Comprar", None))
        self.btnLista.setText(QCoreApplication.translate("MainWindow", u"Lista", None))
        self.label_19.setText("")
        self.btnConfirmarCRUD.setText(QCoreApplication.translate("MainWindow", u"Confirmar", None))
    # retranslateUi

